config/routes.rb
Rails.application.routes.draw do
  resources :trainings_exercises
  resources :trainings
  root "exercises#index"
  resources :exercises
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/exercise.rb
class Exercise < ApplicationRecord
  has_one_attached :image
  has_many_attached :images
  has_many :trainings_exercises
  has_rich_text :body

  enum type: {
    swim: 0,
    ball: 1
  }

end

app/models/training.rb
class Training < ApplicationRecord
  has_many :trainings_exercises
end

app/models/trainings_exercise.rb
class TrainingsExercise < ApplicationRecord
  belongs_to :training
  belongs_to :exercise
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  before_action :set_exercise, only: %i[ show edit update destroy ]
  def index
    @exercise = Exercise.new
    @exercises = Exercise.all.order(created_at: :desc)
  end
  def show
  end

  def new
    @exercise = Exercise.new
  end

  def edit
  end

  def create
    @exercise = Exercise.new(exercise_params)
    @new_exercise = Exercise.new

    respond_to do |format|
      if @exercise.save
        format.html { redirect_to exercise_url(@exercise), notice: "Exercise was successfully created." }
        format.turbo_stream
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @exercise.update(exercise_params)
        format.html { redirect_to exercise_url(@exercise), notice: "Exercise was successfully updated." }
        format.turbo_stream
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @exercise.destroy

    respond_to do |format|
      format.html { redirect_to exercises_url, notice: "Exercise was successfully destroyed." }
      format.turbo_stream
    end
  end

  private
    def set_exercise
      @exercise = Exercise.find(params[:id])
    end

    def exercise_params
      params.require(:exercise).permit(:title, :body, :image, :purpose, :minutes)
    end
end

app/controllers/trainings_controller.rb
class TrainingsController < ApplicationController
  before_action :set_training, only: %i[ show edit update destroy ]

  def index
    @trainings = Training.all
  end

  def show
  end

  def new
    @training = Training.new
  end
  def edit
  end
  def create
    @training = Training.new(training_params)

    respond_to do |format|
      if @training.save
        format.html { redirect_to training_url(@training), notice: "Training was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @training.update(training_params)
        format.html { redirect_to training_url(@training), notice: "Training was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @training.destroy

    respond_to do |format|
      format.html { redirect_to trainings_url, notice: "Training was successfully destroyed." }
    end
  end

  private
    def set_training
      @training = Training.find(params[:id])
    end

    def training_params
      params.require(:training).permit(:trainings_date)
    end
end

app/controllers/trainings_exercises_controller.rb
class TrainingsExercisesController < ApplicationController
  before_action :set_trainings_exercise, only: %i[ show edit update destroy ]
  def index
    @trainings_exercises = TrainingsExercise.all
  end

  def show
  end

  def new
    @trainings_exercise = TrainingsExercise.new
  end

  def edit
  end

  def create
    @trainings_exercise = TrainingsExercise.new(trainings_exercise_params)

    respond_to do |format|
      if @trainings_exercise.save
        format.html { redirect_to trainings_exercise_url(@trainings_exercise), notice: "Trainings exercise was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @trainings_exercise.update(trainings_exercise_params)
        format.html { redirect_to trainings_exercise_url(@trainings_exercise), notice: "Trainings exercise was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @trainings_exercise.destroy

    respond_to do |format|
      format.html { redirect_to trainings_exercises_url, notice: "Trainings exercise was successfully destroyed." }
    end
  end

  private
    def set_trainings_exercise
      @trainings_exercise = TrainingsExercise.find(params[:id])
    end

    def trainings_exercise_params
      params.require(:trainings_exercise).permit(:training_id, :exercise_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/icon_helper.rb
module IconHelper
  def tabler_icon(name, options = {})
    inline_svg_tag("tabler_icons/#{name}", options)
  end
end

app/helpers/trainings_exercises_helper.rb
module TrainingsExercisesHelper
end

app/helpers/trainings_helper.rb
module TrainingsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/exercises/_exercise.html.erb
<%= turbo_frame_tag exercise do %>
	<div id="<%= dom_id exercise %>">
		<p class="my-5">
			<strong class="block font-medium mb-1"><%= exercise.title %></strong>
		</p>
		<p class="my-5">
			Doel:
			<%= exercise.purpose %>
		</p>
		<p class="my-5">
			Duur: <%= exercise.minutes %>
		</p>
		<p class="my-5">
			<%= exercise.body %>
		</p>

		<p class="my-5">
			<%= image_tag(exercise.image, { width: 300, height: 300 }) if exercise.image.attached? %>
		</p>

		<% if action_name != "show" %>
			<div class="flex justify-between content-center mt-3">
				<%= link_to 'Bewerk oefening', edit_exercise_path(exercise), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
				<%= button_to 'Verwijder oefening', exercise_path(exercise), method: :delete, class: "rounded-lg py-3 ml-2 px-5 bg-red-100 inline-block font-medium" %>
			</div>
			<hr class="mt-6">
		<% end %>
	</div>
<% end %>

app/views/exercises/_form.html.erb
<%= turbo_frame_tag "new_exercise" do %>
	<%= form_with(model: exercise, class: "contents") do |form| %>
		<% if exercise.errors.any? %>
			<div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
				<h2><%= pluralize(exercise.errors.count, "error") %> prohibited this exercise from being saved:</h2>

				<ul>
					<% exercise.errors.each do |error| %>
						<li><%= error.full_message %></li>
					<% end %>
				</ul>
			</div>
		<% end %>

		<div class="my-5">
			<%= form.label :title %>
			<%= form.text_field :title, class: "block shadow rounded-lg  border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
		</div>

		<div class="my-5">
			<%= form.label "Doel" %>
			<%= form.text_field :purpose, class: "block shadow rounded-lg border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
		</div>

		<div class="my-5">
			<%= form.label "Duur oefening in minuten" %>
			<%= form.number_field :minutes,in: 1.0..20.0, step: 1.0, class: "block shadow rounded-lg border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
		</div>

		<div class="my-5">
			<%= form.rich_text_area :body , class: "border border-gray-400 p-2 rounded-lg w-full h-32" %>
		</div>

		<div class="my--5">
			<%= form.label :image %>
			<%= form.file_field :image, class: "p-2 rounded-lg" %>
		</div>

		<div class="flex justify-between mt-6">
			<%= form.submit "Opslaan", class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>

			<% if controller.action_name == "new" %>
				<%= link_to 'Overzicht Oefeningen', exercises_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
			<% elsif controller.action_name == "edit" %>
				<%= link_to "Toon oefening", @exercise, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
				<%= link_to "Oefeningen overzicht", exercises_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
			<% end %>
		</div>
	<% end %>
<% end %>

app/views/exercises/create.turbo_stream.erb
<%= turbo_stream.prepend "exercises", partial: "exercises/exercise", locals: { exercise: @exercise } %>

<%= turbo_stream.replace "new_exercise" do %>
	<%= render partial: "exercises/form", locals: { exercise: @new_exercise } %>
<% end %>

app/views/exercises/destroy.turbo_stream.erb
<%= turbo_stream.remove @exercise %>

app/views/exercises/edit.html.erb
<%= turbo_frame_tag @exercise, class: "w-full" do %>
	<%= render "form", exercise: @exercise %>
<% end %>

app/views/exercises/index.html.erb
<div class="w-full">
	<% if notice.present? %>
		<p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
	<% end %>

	<div class="flex justify-between items-center" data-controller="exercise">
		<h1 class="font-bold text-4xl">Oefeningen</h1>
		<btn data-action="click->exercise#toggle"> + </btn>
	</div>

	<div class="max-w-sm hidden" id="new-exercise-form">
		<%= render "form", exercise: @exercise %>
	</div>

	<div id="exercises" class="min-w-full">
		<%= turbo_frame_tag "exercises" do %>
			<%= render @exercises %>
		<% end %>
	</div>
</div>

app/views/exercises/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Nieuwe oefening</h1>

  <%= render "form", exercise: @exercise %>


</div>

app/views/exercises/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @exercise %>

    <%= link_to 'Bewerk oefening', edit_exercise_path(@exercise), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Verwijder oefening', exercise_path(@exercise), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Terug naar overzicht', exercises_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/exercises/update.turbo_stream.erb
<%= turbo_stream.replace dom_id(@exercise), partial: "exercises/exercise", locals: { exercise: @exercise } %>

app/views/layouts/_navbar.html.erb
<nav class="bg-blue-100">
	<div class="container mx-auto px-6 py-2 flex items-center justify-center">
		<div class="md:flex ">
			<%= link_to "Oefening", exercises_path, class:"text-gray-500 hover:text-white mr-4" %>
			<%= link_to "Training", trainings_path, class:"text-gray-500 hover:text-white mr-4" %>
			<%= link_to "Trainingsoefeningen", trainings_exercises_path, class:"text-gray-500 hover:text-white mr-4" %>
		</div>
	</div>
</nav>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WaterpoloExercise</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <main class="container max-w-sm mx-auto mt-8 px-5 flex justify-center">
        <div class=" flex justify-center">
	        <%= yield %>
        </div>
    </main>
  </body>
</html>

app/views/trainings/_form.html.erb
<%= form_with(model: training, class: "contents") do |form| %>
  <% if training.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(training.errors.count, "error") %> prohibited this training from being saved:</h2>

      <ul>
        <% training.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :training_date %>
    <%= form.date_field :trainings_date, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/trainings/_training.html.erb
<div id="<%= dom_id training %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Training date:</strong>
    <%= training.trainings_date %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this training", training, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this training', edit_training_path(training), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/trainings/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing training</h1>

  <%= render "form", training: @training %>

  <%= link_to "Show this training", @training, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to trainings", trainings_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/trainings/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Trainings</h1>
    <%= link_to 'New training', new_training_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="trainings" class="min-w-full">
    <%= render @trainings %>
  </div>
</div>

app/views/trainings/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New training</h1>

  <%= render "form", training: @training %>

  <%= link_to 'Back to trainings', trainings_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/trainings/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @training %>

    <%= link_to 'Edit this training', edit_training_path(@training), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this training', training_path(@training), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to trainings', trainings_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/trainings_exercises/_form.html.erb
<%= form_with(model: trainings_exercise, class: "contents") do |form| %>
  <% if trainings_exercise.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(trainings_exercise.errors.count, "error") %> prohibited this trainings_exercise from being saved:</h2>

      <ul>
        <% trainings_exercise.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label "Training" %>
    <%= form.collection_select :training_id, Training.order(:trainings_date), :id, :trainings_date, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
      <%= form.label "Oefening" %>
      <%= form.collection_select :exercise_id, Exercise.order(:title), :id, :title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/trainings_exercises/_trainings_exercise.html.erb
<div id="<%= dom_id trainings_exercise %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Training:</strong>
    <%= trainings_exercise.training_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Exercise:</strong>
    <%= trainings_exercise.exercise_id %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this trainings exercise", trainings_exercise, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this trainings exercise', edit_trainings_exercise_path(trainings_exercise), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/trainings_exercises/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing trainings exercise</h1>

  <%= render "form", trainings_exercise: @trainings_exercise %>

  <%= link_to "Show this trainings exercise", @trainings_exercise, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to trainings exercises", trainings_exercises_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/trainings_exercises/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Trainings exercises</h1>
    <%= link_to 'New trainings exercise', new_trainings_exercise_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="trainings_exercises" class="min-w-full">
    <%= render @trainings_exercises %>
  </div>
</div>

app/views/trainings_exercises/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New trainings exercise</h1>

  <%= render "form", trainings_exercise: @trainings_exercise %>

  <%= link_to 'Back to trainings exercises', trainings_exercises_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/trainings_exercises/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @trainings_exercise %>

    <%= link_to 'Edit this trainings_exercise', edit_trainings_exercise_path(@trainings_exercise), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this trainings_exercise', trainings_exercise_path(@trainings_exercise), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to trainings_exercises', trainings_exercises_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>